# After changing this file, check it on:
# http://lint.travis-ci.org/
sudo: false
cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip

language: python
python:
  - "2.7"
  - "3.3"

# command to install dependencies
before_install:
# Install miniconda to avoid compiling scipy
  - mkdir -p download
  - cd download
  - wget -c http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - cd ..
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then conda create --yes -q -n pyenv python=2.7 numpy=1.9.2 scipy=0.15.1 nose=1.3.4 pip ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then conda create --yes -q -n pyenv python=3.3 numpy=1.9.2 scipy=0.15.1 nose=1.3.4 pip ; fi
  - source activate pyenv
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install pydot; fi
  - pwd
  - mkdir build && cd build && cmake .. && make && cd ..

script:
  - python --version
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - nosetests -v

#after_script:
after_failure:
  - cat /home/travis/.pip/pip.log
#after_success:

cache: apt
